version: '3.8'
services:

  ### nodeJS app
  webapp:
    restart: unless-stopped
    build: .
    networks:
      - node_network
    
  ### nginx
  proxy:
    restart: unless-stopped
    image: nginx
    ports:
      - 80:${NGINX_PORT}
    depends_on:
      - webapp
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node_network

networks:
  node_network: