version: '3.3'

services:

  ###############
  ### ssr-app ###
  ###############
  ssr-app:
    restart: unless-stopped
    build: ./packages/nft-market/app
    env_file:
      - ./packages/nft-market/app/.env

  ##############
  ### fe-api ###
  ##############
  fe-api:
    restart: unless-stopped
    build: ./packages/nft-market/fe-server
    env_file:
      - ./packages/nft-market/fe-server/.env
    depends_on:
      - fedb
    links:
      - fedb

  ##################
  ### image-api ####
  ##################
  image-api:
    restart: unless-stopped
    build: ./packages/nft-market/img-api-server
    env_file:
      - ./packages/nft-market/img-api-server/.env
    depends_on:
      - imgdb
    links:
      - imgdb

  ################
  ### sol-api ####
  ################
  solana-api:
    restart: unless-stopped
    build: ./packages/nft-market/sol-api-server
    env_file:
      - ./packages/nft-market/sol-api-server/.env
    depends_on:
      - soldb
    links:
      - soldb

  ########################
  ### web server mysql ###
  ########################
  fedb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${WEB_SERVER_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${WEB_SERVER_MYSQL_USER}
      MYSQL_PASSWORD: ${WEB_SERVER_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${WEB_SERVER_MYSQL_DATABASE}
    ports:
      - '3307:3307'
    volumes:
      - ./mysql/fe_db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - fedb:/var/lib/fedb

  #######################
  ### image api mysql ###
  #######################
  imgdb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${IMAGE_API_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${IMAGE_API_MYSQL_USER}
      MYSQL_PASSWORD: ${IMAGE_API_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${IMAGE_API_MYSQL_DATABASE}
    ports:
      - '3308:3308'
    volumes:
      - ./mysql/img_db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - imgdb:/var/lib/imgdb

  ########################
  ### solana api mysql ###
  ########################
  soldb:
    build: ./mysql/sol_db
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SOLANA_API_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${SOLANA_API_MYSQL_USER}
      MYSQL_PASSWORD: ${SOLANA_API_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${SOLANA_API_MYSQL_DATABASE}
    ports:
      - '3309:3309'
    volumes:
      # - ./mysql/sol_db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - soldb:/var/lib/soldb

  #############
  ### nginx ###
  #############
  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - ssr-app
      - fe-api
      - image-api
      - solana-api

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  imgdb:
    driver: local
  fedb:
    driver: local
  soldb:
    driver: local