version: '3.3'

services:
  
  ############
  ### node ###
  ############
  webapp:
    restart: unless-stopped
    build: .
    entrypoint:
      - /bin/sh
      - /usr/src/app/entry_webapp.sh
    volumes:
      - nginx-static:/usr/src/app/packages/nft-market/client/dist

  #############
  ### mysql ###
  #############
  db:
    image: mysql:latest
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db:/var/lib/mysql

  #############
  ### nginx ###
  #############
  proxy:
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-static:/var/www/public

  ######################
  ### pgadmin ###
  ######################


volumes:
  nginx-static: {}
  db:
    driver: local
