version: '3.3'

services:
  
  ############
  ### node ###
  ############
  webapp:
    restart: unless-stopped
    build: .
    entrypoint:
      - /bin/sh
      - /usr/src/app/entry_webapp.sh
    volumes:
      - nginx-static:/usr/src/app/packages/nft-market/client/dist

  ################
  ### postgres ###
  ################
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - '5432:5432'
    volumes:
      - ./.db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db:/var/lib/postgresql/data

  #############
  ### nginx ###
  #############
  proxy:
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-static:/var/www/public

  ######################
  ### pgadmin ###
  ######################
  pgadmin-compose:
    image: dpage/pgadmin4
    # restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "16534:80"
    depends_on:
      - postgres
    tty: true
    volumes:
      - pgadmin:/var/lib/pgadmin/data

volumes:
  pgadmin: {}
  nginx-static: {}
  db:
    driver: local
