version: '3.3'

services:

  ############
  ### node ###
  ############
  webapp:
    restart: unless-stopped
    build: .
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - nginx-static:/usr/src/app/packages/nft-market/client/dist
      - wait-for-it:/usr/src/app
    entrypoint:
      - /bin/sh
      - /usr/src/app/entry_webapp.sh

  #############
  ### mysql ###
  #############
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql:/var/lib/mysql

  #############
  ### nginx ###
  #############
  proxy:
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-static:/var/www/public

volumes:
  wait-for-it: {}
  nginx-static: {}
  mysql:
    driver: local
