version: '3.3'
services:

  ### nodeJS app
  # webapp:
  #   restart: unless-stopped
  #   build: .
  #   networks:
  #     - node_network
    
  ### nginx
  proxy:
    restart: unless-stopped
    image: nginx-latest
    ports:
      - "80:80"
      - "443:443"
    # depends_on:
    #   - webapp
    # volumes:
    #   - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    #   - ./data/certbot/conf:/etc/letsencrypt
    #   - ./data/certbot/www:/var/www/certbot
    # networks:
    #   - node_network
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  ## let's encrypt
#   certbot:
#     image: certbot/certbot
#     volumes:
#       - ./data/certbot/conf:/etc/letsencrypt
#       - ./data/certbot/www:/var/www/certbot
#     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

# networks:
#   node_network: