version: '3.3'

services:

  #############
  ### react ###
  #############
  react:
    build: ./packages/nft-market/client
    volumes:
      - nginx-static:/usr/src/nft-market-react-app/dist

  ##################
  ### web-server ###
  ##################
  web-server:
    restart: unless-stopped
    build: ./packages/nft-market/fe-server
    depends_on:
      - fe-db
    links:
      - fe-db

  ###################
  ### api-server ####
  ###################
  image-api:
    restart: unless-stopped
    build: ./packages/nft-market/img-api-server
    depends_on:
      - img-db
    links:
      - img-db

  ########################
  ### web server mysql ###
  ########################
  fe-db:
    image: mysql:latest
    restart: always
    # env_file:
    #   - .tmp/.fe-db.env
    environment:
      MYSQL_ROOT_PASSWORD: ${WEB_SERVER_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${WEB_SERVER_MYSQL_USER}
      MYSQL_PASSWORD: ${WEB_SERVER_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${WEB_SERVER_MYSQL_DATABASE}
    volumes:
      - ./mysql/fe-db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - fe-db-mysql:/var/lib/fe-db-mysql

  #######################
  ### image api mysql ###
  #######################
  img-db:
    image: mysql:latest
    restart: always
    # env_file:
    #   - .tmp/.img-db.env
    environment:
      MYSQL_ROOT_PASSWORD: ${IMAGE_API_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${IMAGE_API_MYSQL_USER}
      MYSQL_PASSWORD: ${IMAGE_API_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${IMAGE_API_MYSQL_DATABASE}
    volumes:
      - ./mysql/img-db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - img-db-mysql:/var/lib/img-db-mysql

  #############
  ### nginx ###
  #############
  proxy:
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-static:/var/www/public
    depends_on:
      - web-server
      - image-api

volumes:
  wait-for-it: {}
  nginx-static: {}
  img-db-mysql:
    driver: local
  fe-db-mysql:
    driver: local
