version: '3.3'

services:

  #############
  ### react ###
  #############
  react:
    build: ./packages/nft-market/client
    volumes:
      - nginx-static:/usr/src/nft-market-react-app/dist

  ##################
  ### web-server ###
  ##################
  web-server:
    restart: unless-stopped
    build: ./packages/nft-market/fe-server
    env_file:
      - ./packages/nft-market/fe-server/.env
    depends_on:
      - fedb
    links:
      - fedb

  ###################
  ### api-server ####
  ###################
  image-api:
    restart: unless-stopped
    build: ./packages/nft-market/img-api-server
    env_file:
      - ./packages/nft-market/img-api-server/.env
    depends_on:
      - imgdb
    links:
      - imgdb

  ########################
  ### web server mysql ###
  ########################
  fedb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${WEB_SERVER_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${WEB_SERVER_MYSQL_USER}
      MYSQL_PASSWORD: ${WEB_SERVER_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${WEB_SERVER_MYSQL_DATABASE}
    ports:
      - '3307:3307'
    volumes:
      - ./mysql/fe_db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - fedb:/var/lib/fedb

  #######################
  ### image api mysql ###
  #######################
  imgdb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${IMAGE_API_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${IMAGE_API_MYSQL_USER}
      MYSQL_PASSWORD: ${IMAGE_API_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${IMAGE_API_MYSQL_DATABASE}
    ports:
      - '3308:3308'
    volumes:
      - ./mysql/img_db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - imgdb:/var/lib/imgdb

  #############
  ### nginx ###
  #############
  proxy:
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-static:/var/www/public
    depends_on:
      - web-server
      - image-api

volumes:
  wait-for-it: {}
  nginx-static: {}
  imgdb:
    driver: local
  fedb:
    driver: local
