version: '3.3'
services:

  ### nodeJS app
  webapp:
    restart: unless-stopped
    build: .
    networks:
      - node_network

  ### nginx
  proxy:
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - webapp
    networks:
      - node_network

networks:
  node_network: