/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IBarn, IBarnInterface } from "../IBarn";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint16[]",
        name: "tokenIds",
        type: "uint16[]",
      },
    ],
    name: "addManyToBarnAndPack",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "seed",
        type: "uint256",
      },
    ],
    name: "randomWolfOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IBarn__factory {
  static readonly abi = _abi;
  static createInterface(): IBarnInterface {
    return new utils.Interface(_abi) as IBarnInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IBarn {
    return new Contract(address, _abi, signerOrProvider) as IBarn;
  }
}
