/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITraits, ITraitsInterface } from "../ITraits";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ITraits__factory {
  static readonly abi = _abi;
  static createInterface(): ITraitsInterface {
    return new utils.Interface(_abi) as ITraitsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITraits {
    return new Contract(address, _abi, signerOrProvider) as ITraits;
  }
}
