/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IWoolf, IWoolfInterface } from "../IWoolf";

const _abi = [
  {
    inputs: [],
    name: "getPaidTokens",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "getTokenTraits",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "isSheep",
            type: "bool",
          },
          {
            internalType: "uint8",
            name: "fur",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "head",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "ears",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "eyes",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "nose",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "mouth",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "neck",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "feet",
            type: "uint8",
          },
          {
            internalType: "uint8",
            name: "alphaIndex",
            type: "uint8",
          },
        ],
        internalType: "struct IWoolf.SheepWolf",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IWoolf__factory {
  static readonly abi = _abi;
  static createInterface(): IWoolfInterface {
    return new utils.Interface(_abi) as IWoolfInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IWoolf {
    return new Contract(address, _abi, signerOrProvider) as IWoolf;
  }
}
